# Generated by Django 5.2.6 on 2025-11-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='progress_percent',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Tecnología', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='es', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
